/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.analytics.jooq.tables;


import com.urlshortener.analytics.jooq.Indexes;
import com.urlshortener.analytics.jooq.Keys;
import com.urlshortener.analytics.jooq.Public;
import com.urlshortener.analytics.jooq.tables.records.ClickAnalyticsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function18;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClickAnalytics extends TableImpl<ClickAnalyticsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.click_analytics</code>
     */
    public static final ClickAnalytics CLICK_ANALYTICS = new ClickAnalytics();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClickAnalyticsRecord> getRecordType() {
        return ClickAnalyticsRecord.class;
    }

    /**
     * The column <code>public.click_analytics.id</code>.
     */
    public final TableField<ClickAnalyticsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.click_analytics.short_code</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> SHORT_CODE = createField(DSL.name("short_code"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.click_analytics.timestamp</code>.
     */
    public final TableField<ClickAnalyticsRecord, OffsetDateTime> TIMESTAMP = createField(DSL.name("timestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.click_analytics.user_agent</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> USER_AGENT = createField(DSL.name("user_agent"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.click_analytics.device_type</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> DEVICE_TYPE = createField(DSL.name("device_type"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.click_analytics.browser</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> BROWSER = createField(DSL.name("browser"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.click_analytics.operating_system</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> OPERATING_SYSTEM = createField(DSL.name("operating_system"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.click_analytics.geo_country</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> GEO_COUNTRY = createField(DSL.name("geo_country"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.click_analytics.geo_city</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> GEO_CITY = createField(DSL.name("geo_city"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.click_analytics.referrer</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> REFERRER = createField(DSL.name("referrer"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.click_analytics.is_bot</code>.
     */
    public final TableField<ClickAnalyticsRecord, Boolean> IS_BOT = createField(DSL.name("is_bot"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.click_analytics.variant</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> VARIANT = createField(DSL.name("variant"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.click_analytics.utm_source</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> UTM_SOURCE = createField(DSL.name("utm_source"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.click_analytics.utm_medium</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> UTM_MEDIUM = createField(DSL.name("utm_medium"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.click_analytics.utm_campaign</code>.
     */
    public final TableField<ClickAnalyticsRecord, String> UTM_CAMPAIGN = createField(DSL.name("utm_campaign"), SQLDataType.VARCHAR(100).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.click_analytics.url_id</code>.
     */
    public final TableField<ClickAnalyticsRecord, UUID> URL_ID = createField(DSL.name("url_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.click_analytics.campaign_id</code>.
     */
    public final TableField<ClickAnalyticsRecord, UUID> CAMPAIGN_ID = createField(DSL.name("campaign_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.click_analytics.ab_test_id</code>.
     */
    public final TableField<ClickAnalyticsRecord, UUID> AB_TEST_ID = createField(DSL.name("ab_test_id"), SQLDataType.UUID, this, "");

    private ClickAnalytics(Name alias, Table<ClickAnalyticsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ClickAnalytics(Name alias, Table<ClickAnalyticsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.click_analytics</code> table reference
     */
    public ClickAnalytics(String alias) {
        this(DSL.name(alias), CLICK_ANALYTICS);
    }

    /**
     * Create an aliased <code>public.click_analytics</code> table reference
     */
    public ClickAnalytics(Name alias) {
        this(alias, CLICK_ANALYTICS);
    }

    /**
     * Create a <code>public.click_analytics</code> table reference
     */
    public ClickAnalytics() {
        this(DSL.name("click_analytics"), null);
    }

    public <O extends Record> ClickAnalytics(Table<O> child, ForeignKey<O, ClickAnalyticsRecord> key) {
        super(child, key, CLICK_ANALYTICS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CLICK_ANALYTICS_AB_TEST_ID, Indexes.IDX_CLICK_ANALYTICS_CAMPAIGN_ID, Indexes.IDX_CLICK_ANALYTICS_SHORT_CODE, Indexes.IDX_CLICK_ANALYTICS_SHORT_CODE_VARIANT, Indexes.IDX_CLICK_ANALYTICS_TIMESTAMP, Indexes.IDX_CLICK_ANALYTICS_URL_ID, Indexes.IDX_CLICK_ANALYTICS_UTM_CAMPAIGN, Indexes.IDX_CLICK_ANALYTICS_UTM_SOURCE);
    }

    @Override
    public UniqueKey<ClickAnalyticsRecord> getPrimaryKey() {
        return Keys.CLICK_ANALYTICS_PKEY;
    }

    @Override
    public ClickAnalytics as(String alias) {
        return new ClickAnalytics(DSL.name(alias), this);
    }

    @Override
    public ClickAnalytics as(Name alias) {
        return new ClickAnalytics(alias, this);
    }

    @Override
    public ClickAnalytics as(Table<?> alias) {
        return new ClickAnalytics(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ClickAnalytics rename(String name) {
        return new ClickAnalytics(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClickAnalytics rename(Name name) {
        return new ClickAnalytics(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ClickAnalytics rename(Table<?> name) {
        return new ClickAnalytics(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<UUID, String, OffsetDateTime, String, String, String, String, String, String, String, Boolean, String, String, String, String, UUID, UUID, UUID> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function18<? super UUID, ? super String, ? super OffsetDateTime, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super String, ? super String, ? super String, ? super String, ? super UUID, ? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function18<? super UUID, ? super String, ? super OffsetDateTime, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Boolean, ? super String, ? super String, ? super String, ? super String, ? super UUID, ? super UUID, ? super UUID, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
