/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables;


import com.urlshortener.core.jooq.Indexes;
import com.urlshortener.core.jooq.Keys;
import com.urlshortener.core.jooq.Public;
import com.urlshortener.core.jooq.tables.records.AbTestsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbTests extends TableImpl<AbTestsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ab_tests</code>
     */
    public static final AbTests AB_TESTS = new AbTests();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AbTestsRecord> getRecordType() {
        return AbTestsRecord.class;
    }

    /**
     * The column <code>public.ab_tests.id</code>.
     */
    public final TableField<AbTestsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.ab_tests.url_mapping_id</code>.
     */
    public final TableField<AbTestsRecord, UUID> URL_MAPPING_ID = createField(DSL.name("url_mapping_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ab_tests.name</code>.
     */
    public final TableField<AbTestsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.ab_tests.status</code>.
     */
    public final TableField<AbTestsRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.ab_tests.winning_variant</code>.
     */
    public final TableField<AbTestsRecord, String> WINNING_VARIANT = createField(DSL.name("winning_variant"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.ab_tests.cookie_ttl_seconds</code>.
     */
    public final TableField<AbTestsRecord, Integer> COOKIE_TTL_SECONDS = createField(DSL.name("cookie_ttl_seconds"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("2592000"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ab_tests.created_at</code>.
     */
    public final TableField<AbTestsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.ab_tests.updated_at</code>.
     */
    public final TableField<AbTestsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AbTests(Name alias, Table<AbTestsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AbTests(Name alias, Table<AbTestsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ab_tests</code> table reference
     */
    public AbTests(String alias) {
        this(DSL.name(alias), AB_TESTS);
    }

    /**
     * Create an aliased <code>public.ab_tests</code> table reference
     */
    public AbTests(Name alias) {
        this(alias, AB_TESTS);
    }

    /**
     * Create a <code>public.ab_tests</code> table reference
     */
    public AbTests() {
        this(DSL.name("ab_tests"), null);
    }

    public <O extends Record> AbTests(Table<O> child, ForeignKey<O, AbTestsRecord> key) {
        super(child, key, AB_TESTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_AB_TESTS_URL_MAPPING);
    }

    @Override
    public UniqueKey<AbTestsRecord> getPrimaryKey() {
        return Keys.AB_TESTS_PKEY;
    }

    @Override
    public List<UniqueKey<AbTestsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.AB_TESTS_URL_MAPPING_ID_KEY);
    }

    @Override
    public List<ForeignKey<AbTestsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AB_TESTS__AB_TESTS_URL_MAPPING_ID_FKEY);
    }

    private transient UrlMappings _urlMappings;

    /**
     * Get the implicit join path to the <code>public.url_mappings</code> table.
     */
    public UrlMappings urlMappings() {
        if (_urlMappings == null)
            _urlMappings = new UrlMappings(this, Keys.AB_TESTS__AB_TESTS_URL_MAPPING_ID_FKEY);

        return _urlMappings;
    }

    @Override
    public AbTests as(String alias) {
        return new AbTests(DSL.name(alias), this);
    }

    @Override
    public AbTests as(Name alias) {
        return new AbTests(alias, this);
    }

    @Override
    public AbTests as(Table<?> alias) {
        return new AbTests(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AbTests rename(String name) {
        return new AbTests(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AbTests rename(Name name) {
        return new AbTests(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AbTests rename(Table<?> name) {
        return new AbTests(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, String, String, String, Integer, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super Integer, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super UUID, ? super UUID, ? super String, ? super String, ? super String, ? super Integer, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
