/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables;


import com.urlshortener.core.jooq.Indexes;
import com.urlshortener.core.jooq.Keys;
import com.urlshortener.core.jooq.Public;
import com.urlshortener.core.jooq.tables.records.AbVariantsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbVariants extends TableImpl<AbVariantsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.ab_variants</code>
     */
    public static final AbVariants AB_VARIANTS = new AbVariants();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AbVariantsRecord> getRecordType() {
        return AbVariantsRecord.class;
    }

    /**
     * The column <code>public.ab_variants.id</code>.
     */
    public final TableField<AbVariantsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.ab_variants.ab_test_id</code>.
     */
    public final TableField<AbVariantsRecord, UUID> AB_TEST_ID = createField(DSL.name("ab_test_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.ab_variants.variant_key</code>.
     */
    public final TableField<AbVariantsRecord, String> VARIANT_KEY = createField(DSL.name("variant_key"), SQLDataType.VARCHAR(10).nullable(false), this, "");

    /**
     * The column <code>public.ab_variants.destination_url</code>.
     */
    public final TableField<AbVariantsRecord, String> DESTINATION_URL = createField(DSL.name("destination_url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.ab_variants.weight</code>.
     */
    public final TableField<AbVariantsRecord, Integer> WEIGHT = createField(DSL.name("weight"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("50"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.ab_variants.is_control</code>.
     */
    public final TableField<AbVariantsRecord, Boolean> IS_CONTROL = createField(DSL.name("is_control"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.ab_variants.created_at</code>.
     */
    public final TableField<AbVariantsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private AbVariants(Name alias, Table<AbVariantsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AbVariants(Name alias, Table<AbVariantsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.ab_variants</code> table reference
     */
    public AbVariants(String alias) {
        this(DSL.name(alias), AB_VARIANTS);
    }

    /**
     * Create an aliased <code>public.ab_variants</code> table reference
     */
    public AbVariants(Name alias) {
        this(alias, AB_VARIANTS);
    }

    /**
     * Create a <code>public.ab_variants</code> table reference
     */
    public AbVariants() {
        this(DSL.name("ab_variants"), null);
    }

    public <O extends Record> AbVariants(Table<O> child, ForeignKey<O, AbVariantsRecord> key) {
        super(child, key, AB_VARIANTS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_AB_VARIANTS_TEST_ID);
    }

    @Override
    public UniqueKey<AbVariantsRecord> getPrimaryKey() {
        return Keys.AB_VARIANTS_PKEY;
    }

    @Override
    public List<ForeignKey<AbVariantsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.AB_VARIANTS__AB_VARIANTS_AB_TEST_ID_FKEY);
    }

    private transient AbTests _abTests;

    /**
     * Get the implicit join path to the <code>public.ab_tests</code> table.
     */
    public AbTests abTests() {
        if (_abTests == null)
            _abTests = new AbTests(this, Keys.AB_VARIANTS__AB_VARIANTS_AB_TEST_ID_FKEY);

        return _abTests;
    }

    @Override
    public AbVariants as(String alias) {
        return new AbVariants(DSL.name(alias), this);
    }

    @Override
    public AbVariants as(Name alias) {
        return new AbVariants(alias, this);
    }

    @Override
    public AbVariants as(Table<?> alias) {
        return new AbVariants(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AbVariants rename(String name) {
        return new AbVariants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AbVariants rename(Name name) {
        return new AbVariants(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AbVariants rename(Table<?> name) {
        return new AbVariants(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, String, Integer, Boolean, OffsetDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super UUID, ? super UUID, ? super String, ? super String, ? super Integer, ? super Boolean, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super UUID, ? super UUID, ? super String, ? super String, ? super Integer, ? super Boolean, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
