/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables;


import com.urlshortener.core.jooq.Indexes;
import com.urlshortener.core.jooq.Keys;
import com.urlshortener.core.jooq.Public;
import com.urlshortener.core.jooq.tables.records.CampaignsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Campaigns extends TableImpl<CampaignsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.campaigns</code>
     */
    public static final Campaigns CAMPAIGNS = new Campaigns();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CampaignsRecord> getRecordType() {
        return CampaignsRecord.class;
    }

    /**
     * The column <code>public.campaigns.id</code>.
     */
    public final TableField<CampaignsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.campaigns.user_id</code>.
     */
    public final TableField<CampaignsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.campaigns.name</code>.
     */
    public final TableField<CampaignsRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.campaigns.description</code>.
     */
    public final TableField<CampaignsRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.campaigns.created_at</code>.
     */
    public final TableField<CampaignsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.campaigns.updated_at</code>.
     */
    public final TableField<CampaignsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Campaigns(Name alias, Table<CampaignsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Campaigns(Name alias, Table<CampaignsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.campaigns</code> table reference
     */
    public Campaigns(String alias) {
        this(DSL.name(alias), CAMPAIGNS);
    }

    /**
     * Create an aliased <code>public.campaigns</code> table reference
     */
    public Campaigns(Name alias) {
        this(alias, CAMPAIGNS);
    }

    /**
     * Create a <code>public.campaigns</code> table reference
     */
    public Campaigns() {
        this(DSL.name("campaigns"), null);
    }

    public <O extends Record> Campaigns(Table<O> child, ForeignKey<O, CampaignsRecord> key) {
        super(child, key, CAMPAIGNS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_CAMPAIGNS_USER_NAME, Indexes.IDX_CAMPAIGNS_USERS_ID);
    }

    @Override
    public UniqueKey<CampaignsRecord> getPrimaryKey() {
        return Keys.CAMPAIGNS_PKEY;
    }

    @Override
    public Campaigns as(String alias) {
        return new Campaigns(DSL.name(alias), this);
    }

    @Override
    public Campaigns as(Name alias) {
        return new Campaigns(alias, this);
    }

    @Override
    public Campaigns as(Table<?> alias) {
        return new Campaigns(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaigns rename(String name) {
        return new Campaigns(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaigns rename(Name name) {
        return new Campaigns(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Campaigns rename(Table<?> name) {
        return new Campaigns(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super UUID, ? super UUID, ? super String, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super UUID, ? super UUID, ? super String, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
