/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables;


import com.urlshortener.core.jooq.Indexes;
import com.urlshortener.core.jooq.Keys;
import com.urlshortener.core.jooq.Public;
import com.urlshortener.core.jooq.tables.records.UrlMappingsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UrlMappings extends TableImpl<UrlMappingsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.url_mappings</code>
     */
    public static final UrlMappings URL_MAPPINGS = new UrlMappings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UrlMappingsRecord> getRecordType() {
        return UrlMappingsRecord.class;
    }

    /**
     * The column <code>public.url_mappings.id</code>.
     */
    public final TableField<UrlMappingsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.url_mappings.short_code</code>.
     */
    public final TableField<UrlMappingsRecord, String> SHORT_CODE = createField(DSL.name("short_code"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.url_mappings.destination_url</code>.
     */
    public final TableField<UrlMappingsRecord, String> DESTINATION_URL = createField(DSL.name("destination_url"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.url_mappings.tenant_id</code>.
     */
    public final TableField<UrlMappingsRecord, String> TENANT_ID = createField(DSL.name("tenant_id"), SQLDataType.VARCHAR(50).nullable(false).defaultValue(DSL.field(DSL.raw("'default'::character varying"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.url_mappings.user_id</code>.
     */
    public final TableField<UrlMappingsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.url_mappings.is_active</code>.
     */
    public final TableField<UrlMappingsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.url_mappings.expires_at</code>.
     */
    public final TableField<UrlMappingsRecord, OffsetDateTime> EXPIRES_AT = createField(DSL.name("expires_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.url_mappings.created_at</code>.
     */
    public final TableField<UrlMappingsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.url_mappings.updated_at</code>.
     */
    public final TableField<UrlMappingsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.url_mappings.campaign_id</code>.
     */
    public final TableField<UrlMappingsRecord, UUID> CAMPAIGN_ID = createField(DSL.name("campaign_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.url_mappings.is_ab_test</code>.
     */
    public final TableField<UrlMappingsRecord, Boolean> IS_AB_TEST = createField(DSL.name("is_ab_test"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.url_mappings.smart_rules</code>.
     */
    public final TableField<UrlMappingsRecord, JSONB> SMART_RULES = createField(DSL.name("smart_rules"), SQLDataType.JSONB, this, "");

    private UrlMappings(Name alias, Table<UrlMappingsRecord> aliased) {
        this(alias, aliased, null);
    }

    private UrlMappings(Name alias, Table<UrlMappingsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.url_mappings</code> table reference
     */
    public UrlMappings(String alias) {
        this(DSL.name(alias), URL_MAPPINGS);
    }

    /**
     * Create an aliased <code>public.url_mappings</code> table reference
     */
    public UrlMappings(Name alias) {
        this(alias, URL_MAPPINGS);
    }

    /**
     * Create a <code>public.url_mappings</code> table reference
     */
    public UrlMappings() {
        this(DSL.name("url_mappings"), null);
    }

    public <O extends Record> UrlMappings(Table<O> child, ForeignKey<O, UrlMappingsRecord> key) {
        super(child, key, URL_MAPPINGS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_URL_MAPPINGS_CAMPAIGN_ID, Indexes.IDX_URL_MAPPINGS_SHORT_CODE, Indexes.IDX_URL_MAPPINGS_USER_ID);
    }

    @Override
    public UniqueKey<UrlMappingsRecord> getPrimaryKey() {
        return Keys.URL_MAPPINGS_PKEY;
    }

    @Override
    public List<UniqueKey<UrlMappingsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.URL_MAPPINGS_SHORT_CODE_KEY);
    }

    @Override
    public List<ForeignKey<UrlMappingsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.URL_MAPPINGS__URL_MAPPINGS_CAMPAIGN_ID_FKEY);
    }

    private transient Campaigns _campaigns;

    /**
     * Get the implicit join path to the <code>public.campaigns</code> table.
     */
    public Campaigns campaigns() {
        if (_campaigns == null)
            _campaigns = new Campaigns(this, Keys.URL_MAPPINGS__URL_MAPPINGS_CAMPAIGN_ID_FKEY);

        return _campaigns;
    }

    @Override
    public UrlMappings as(String alias) {
        return new UrlMappings(DSL.name(alias), this);
    }

    @Override
    public UrlMappings as(Name alias) {
        return new UrlMappings(alias, this);
    }

    @Override
    public UrlMappings as(Table<?> alias) {
        return new UrlMappings(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UrlMappings rename(String name) {
        return new UrlMappings(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UrlMappings rename(Name name) {
        return new UrlMappings(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UrlMappings rename(Table<?> name) {
        return new UrlMappings(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<UUID, String, String, String, UUID, Boolean, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID, Boolean, JSONB> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super UUID, ? super String, ? super String, ? super String, ? super UUID, ? super Boolean, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super UUID, ? super Boolean, ? super JSONB, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super UUID, ? super String, ? super String, ? super String, ? super UUID, ? super Boolean, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super UUID, ? super Boolean, ? super JSONB, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
