/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables.records;


import com.urlshortener.core.jooq.tables.AbTests;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbTestsRecord extends UpdatableRecordImpl<AbTestsRecord> implements Record8<UUID, UUID, String, String, String, Integer, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ab_tests.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ab_tests.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.ab_tests.url_mapping_id</code>.
     */
    public void setUrlMappingId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ab_tests.url_mapping_id</code>.
     */
    public UUID getUrlMappingId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.ab_tests.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ab_tests.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ab_tests.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ab_tests.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.ab_tests.winning_variant</code>.
     */
    public void setWinningVariant(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ab_tests.winning_variant</code>.
     */
    public String getWinningVariant() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.ab_tests.cookie_ttl_seconds</code>.
     */
    public void setCookieTtlSeconds(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ab_tests.cookie_ttl_seconds</code>.
     */
    public Integer getCookieTtlSeconds() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.ab_tests.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ab_tests.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.ab_tests.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.ab_tests.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<UUID, UUID, String, String, String, Integer, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<UUID, UUID, String, String, String, Integer, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AbTests.AB_TESTS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return AbTests.AB_TESTS.URL_MAPPING_ID;
    }

    @Override
    public Field<String> field3() {
        return AbTests.AB_TESTS.NAME;
    }

    @Override
    public Field<String> field4() {
        return AbTests.AB_TESTS.STATUS;
    }

    @Override
    public Field<String> field5() {
        return AbTests.AB_TESTS.WINNING_VARIANT;
    }

    @Override
    public Field<Integer> field6() {
        return AbTests.AB_TESTS.COOKIE_TTL_SECONDS;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return AbTests.AB_TESTS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return AbTests.AB_TESTS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUrlMappingId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public String component5() {
        return getWinningVariant();
    }

    @Override
    public Integer component6() {
        return getCookieTtlSeconds();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component8() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUrlMappingId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public String value5() {
        return getWinningVariant();
    }

    @Override
    public Integer value6() {
        return getCookieTtlSeconds();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value8() {
        return getUpdatedAt();
    }

    @Override
    public AbTestsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AbTestsRecord value2(UUID value) {
        setUrlMappingId(value);
        return this;
    }

    @Override
    public AbTestsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public AbTestsRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public AbTestsRecord value5(String value) {
        setWinningVariant(value);
        return this;
    }

    @Override
    public AbTestsRecord value6(Integer value) {
        setCookieTtlSeconds(value);
        return this;
    }

    @Override
    public AbTestsRecord value7(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AbTestsRecord value8(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public AbTestsRecord values(UUID value1, UUID value2, String value3, String value4, String value5, Integer value6, OffsetDateTime value7, OffsetDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AbTestsRecord
     */
    public AbTestsRecord() {
        super(AbTests.AB_TESTS);
    }

    /**
     * Create a detached, initialised AbTestsRecord
     */
    public AbTestsRecord(UUID id, UUID urlMappingId, String name, String status, String winningVariant, Integer cookieTtlSeconds, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(AbTests.AB_TESTS);

        setId(id);
        setUrlMappingId(urlMappingId);
        setName(name);
        setStatus(status);
        setWinningVariant(winningVariant);
        setCookieTtlSeconds(cookieTtlSeconds);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
