/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables.records;


import com.urlshortener.core.jooq.tables.AbVariants;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AbVariantsRecord extends UpdatableRecordImpl<AbVariantsRecord> implements Record7<UUID, UUID, String, String, Integer, Boolean, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.ab_variants.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.ab_variants.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.ab_variants.ab_test_id</code>.
     */
    public void setAbTestId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.ab_variants.ab_test_id</code>.
     */
    public UUID getAbTestId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.ab_variants.variant_key</code>.
     */
    public void setVariantKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.ab_variants.variant_key</code>.
     */
    public String getVariantKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.ab_variants.destination_url</code>.
     */
    public void setDestinationUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.ab_variants.destination_url</code>.
     */
    public String getDestinationUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.ab_variants.weight</code>.
     */
    public void setWeight(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.ab_variants.weight</code>.
     */
    public Integer getWeight() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.ab_variants.is_control</code>.
     */
    public void setIsControl(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.ab_variants.is_control</code>.
     */
    public Boolean getIsControl() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.ab_variants.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.ab_variants.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, String, String, Integer, Boolean, OffsetDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, UUID, String, String, Integer, Boolean, OffsetDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return AbVariants.AB_VARIANTS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return AbVariants.AB_VARIANTS.AB_TEST_ID;
    }

    @Override
    public Field<String> field3() {
        return AbVariants.AB_VARIANTS.VARIANT_KEY;
    }

    @Override
    public Field<String> field4() {
        return AbVariants.AB_VARIANTS.DESTINATION_URL;
    }

    @Override
    public Field<Integer> field5() {
        return AbVariants.AB_VARIANTS.WEIGHT;
    }

    @Override
    public Field<Boolean> field6() {
        return AbVariants.AB_VARIANTS.IS_CONTROL;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return AbVariants.AB_VARIANTS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getAbTestId();
    }

    @Override
    public String component3() {
        return getVariantKey();
    }

    @Override
    public String component4() {
        return getDestinationUrl();
    }

    @Override
    public Integer component5() {
        return getWeight();
    }

    @Override
    public Boolean component6() {
        return getIsControl();
    }

    @Override
    public OffsetDateTime component7() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getAbTestId();
    }

    @Override
    public String value3() {
        return getVariantKey();
    }

    @Override
    public String value4() {
        return getDestinationUrl();
    }

    @Override
    public Integer value5() {
        return getWeight();
    }

    @Override
    public Boolean value6() {
        return getIsControl();
    }

    @Override
    public OffsetDateTime value7() {
        return getCreatedAt();
    }

    @Override
    public AbVariantsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AbVariantsRecord value2(UUID value) {
        setAbTestId(value);
        return this;
    }

    @Override
    public AbVariantsRecord value3(String value) {
        setVariantKey(value);
        return this;
    }

    @Override
    public AbVariantsRecord value4(String value) {
        setDestinationUrl(value);
        return this;
    }

    @Override
    public AbVariantsRecord value5(Integer value) {
        setWeight(value);
        return this;
    }

    @Override
    public AbVariantsRecord value6(Boolean value) {
        setIsControl(value);
        return this;
    }

    @Override
    public AbVariantsRecord value7(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public AbVariantsRecord values(UUID value1, UUID value2, String value3, String value4, Integer value5, Boolean value6, OffsetDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AbVariantsRecord
     */
    public AbVariantsRecord() {
        super(AbVariants.AB_VARIANTS);
    }

    /**
     * Create a detached, initialised AbVariantsRecord
     */
    public AbVariantsRecord(UUID id, UUID abTestId, String variantKey, String destinationUrl, Integer weight, Boolean isControl, OffsetDateTime createdAt) {
        super(AbVariants.AB_VARIANTS);

        setId(id);
        setAbTestId(abTestId);
        setVariantKey(variantKey);
        setDestinationUrl(destinationUrl);
        setWeight(weight);
        setIsControl(isControl);
        setCreatedAt(createdAt);
        resetChangedOnNotNull();
    }
}
