/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables.records;


import com.urlshortener.core.jooq.tables.Campaigns;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CampaignsRecord extends UpdatableRecordImpl<CampaignsRecord> implements Record6<UUID, UUID, String, String, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.campaigns.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.campaigns.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.campaigns.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.campaigns.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.campaigns.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.campaigns.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.campaigns.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.campaigns.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.campaigns.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.campaigns.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.campaigns.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.campaigns.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, UUID, String, String, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, UUID, String, String, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Campaigns.CAMPAIGNS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return Campaigns.CAMPAIGNS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return Campaigns.CAMPAIGNS.NAME;
    }

    @Override
    public Field<String> field4() {
        return Campaigns.CAMPAIGNS.DESCRIPTION;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return Campaigns.CAMPAIGNS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Campaigns.CAMPAIGNS.UPDATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public OffsetDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getUpdatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public OffsetDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getUpdatedAt();
    }

    @Override
    public CampaignsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public CampaignsRecord value2(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public CampaignsRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public CampaignsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public CampaignsRecord value5(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public CampaignsRecord value6(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public CampaignsRecord values(UUID value1, UUID value2, String value3, String value4, OffsetDateTime value5, OffsetDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CampaignsRecord
     */
    public CampaignsRecord() {
        super(Campaigns.CAMPAIGNS);
    }

    /**
     * Create a detached, initialised CampaignsRecord
     */
    public CampaignsRecord(UUID id, UUID userId, String name, String description, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Campaigns.CAMPAIGNS);

        setId(id);
        setUserId(userId);
        setName(name);
        setDescription(description);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
