/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq.tables.records;


import com.urlshortener.core.jooq.tables.UrlMappings;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UrlMappingsRecord extends UpdatableRecordImpl<UrlMappingsRecord> implements Record12<UUID, String, String, String, UUID, Boolean, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID, Boolean, JSONB> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.url_mappings.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.url_mappings.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.url_mappings.short_code</code>.
     */
    public void setShortCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.url_mappings.short_code</code>.
     */
    public String getShortCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.url_mappings.destination_url</code>.
     */
    public void setDestinationUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.url_mappings.destination_url</code>.
     */
    public String getDestinationUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.url_mappings.tenant_id</code>.
     */
    public void setTenantId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.url_mappings.tenant_id</code>.
     */
    public String getTenantId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.url_mappings.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.url_mappings.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.url_mappings.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.url_mappings.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.url_mappings.expires_at</code>.
     */
    public void setExpiresAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.url_mappings.expires_at</code>.
     */
    public OffsetDateTime getExpiresAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.url_mappings.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.url_mappings.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.url_mappings.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.url_mappings.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.url_mappings.campaign_id</code>.
     */
    public void setCampaignId(UUID value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.url_mappings.campaign_id</code>.
     */
    public UUID getCampaignId() {
        return (UUID) get(9);
    }

    /**
     * Setter for <code>public.url_mappings.is_ab_test</code>.
     */
    public void setIsAbTest(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.url_mappings.is_ab_test</code>.
     */
    public Boolean getIsAbTest() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.url_mappings.smart_rules</code>.
     */
    public void setSmartRules(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.url_mappings.smart_rules</code>.
     */
    public JSONB getSmartRules() {
        return (JSONB) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<UUID, String, String, String, UUID, Boolean, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID, Boolean, JSONB> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<UUID, String, String, String, UUID, Boolean, OffsetDateTime, OffsetDateTime, OffsetDateTime, UUID, Boolean, JSONB> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UrlMappings.URL_MAPPINGS.ID;
    }

    @Override
    public Field<String> field2() {
        return UrlMappings.URL_MAPPINGS.SHORT_CODE;
    }

    @Override
    public Field<String> field3() {
        return UrlMappings.URL_MAPPINGS.DESTINATION_URL;
    }

    @Override
    public Field<String> field4() {
        return UrlMappings.URL_MAPPINGS.TENANT_ID;
    }

    @Override
    public Field<UUID> field5() {
        return UrlMappings.URL_MAPPINGS.USER_ID;
    }

    @Override
    public Field<Boolean> field6() {
        return UrlMappings.URL_MAPPINGS.IS_ACTIVE;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return UrlMappings.URL_MAPPINGS.EXPIRES_AT;
    }

    @Override
    public Field<OffsetDateTime> field8() {
        return UrlMappings.URL_MAPPINGS.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field9() {
        return UrlMappings.URL_MAPPINGS.UPDATED_AT;
    }

    @Override
    public Field<UUID> field10() {
        return UrlMappings.URL_MAPPINGS.CAMPAIGN_ID;
    }

    @Override
    public Field<Boolean> field11() {
        return UrlMappings.URL_MAPPINGS.IS_AB_TEST;
    }

    @Override
    public Field<JSONB> field12() {
        return UrlMappings.URL_MAPPINGS.SMART_RULES;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getShortCode();
    }

    @Override
    public String component3() {
        return getDestinationUrl();
    }

    @Override
    public String component4() {
        return getTenantId();
    }

    @Override
    public UUID component5() {
        return getUserId();
    }

    @Override
    public Boolean component6() {
        return getIsActive();
    }

    @Override
    public OffsetDateTime component7() {
        return getExpiresAt();
    }

    @Override
    public OffsetDateTime component8() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component9() {
        return getUpdatedAt();
    }

    @Override
    public UUID component10() {
        return getCampaignId();
    }

    @Override
    public Boolean component11() {
        return getIsAbTest();
    }

    @Override
    public JSONB component12() {
        return getSmartRules();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getShortCode();
    }

    @Override
    public String value3() {
        return getDestinationUrl();
    }

    @Override
    public String value4() {
        return getTenantId();
    }

    @Override
    public UUID value5() {
        return getUserId();
    }

    @Override
    public Boolean value6() {
        return getIsActive();
    }

    @Override
    public OffsetDateTime value7() {
        return getExpiresAt();
    }

    @Override
    public OffsetDateTime value8() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value9() {
        return getUpdatedAt();
    }

    @Override
    public UUID value10() {
        return getCampaignId();
    }

    @Override
    public Boolean value11() {
        return getIsAbTest();
    }

    @Override
    public JSONB value12() {
        return getSmartRules();
    }

    @Override
    public UrlMappingsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value2(String value) {
        setShortCode(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value3(String value) {
        setDestinationUrl(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value4(String value) {
        setTenantId(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value5(UUID value) {
        setUserId(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value6(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value7(OffsetDateTime value) {
        setExpiresAt(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value8(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value9(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value10(UUID value) {
        setCampaignId(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value11(Boolean value) {
        setIsAbTest(value);
        return this;
    }

    @Override
    public UrlMappingsRecord value12(JSONB value) {
        setSmartRules(value);
        return this;
    }

    @Override
    public UrlMappingsRecord values(UUID value1, String value2, String value3, String value4, UUID value5, Boolean value6, OffsetDateTime value7, OffsetDateTime value8, OffsetDateTime value9, UUID value10, Boolean value11, JSONB value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UrlMappingsRecord
     */
    public UrlMappingsRecord() {
        super(UrlMappings.URL_MAPPINGS);
    }

    /**
     * Create a detached, initialised UrlMappingsRecord
     */
    public UrlMappingsRecord(UUID id, String shortCode, String destinationUrl, String tenantId, UUID userId, Boolean isActive, OffsetDateTime expiresAt, OffsetDateTime createdAt, OffsetDateTime updatedAt, UUID campaignId, Boolean isAbTest, JSONB smartRules) {
        super(UrlMappings.URL_MAPPINGS);

        setId(id);
        setShortCode(shortCode);
        setDestinationUrl(destinationUrl);
        setTenantId(tenantId);
        setUserId(userId);
        setIsActive(isActive);
        setExpiresAt(expiresAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setCampaignId(campaignId);
        setIsAbTest(isAbTest);
        setSmartRules(smartRules);
        resetChangedOnNotNull();
    }
}
