/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.analytics.jooq.tables.records;


import com.urlshortener.analytics.jooq.tables.ClickAnalytics;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClickAnalyticsRecord extends UpdatableRecordImpl<ClickAnalyticsRecord> implements Record18<UUID, String, OffsetDateTime, String, String, String, String, String, String, String, Boolean, String, String, String, String, UUID, UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.click_analytics.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.click_analytics.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.click_analytics.short_code</code>.
     */
    public void setShortCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.click_analytics.short_code</code>.
     */
    public String getShortCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.click_analytics.timestamp</code>.
     */
    public void setTimestamp(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.click_analytics.timestamp</code>.
     */
    public OffsetDateTime getTimestamp() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.click_analytics.user_agent</code>.
     */
    public void setUserAgent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.click_analytics.user_agent</code>.
     */
    public String getUserAgent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.click_analytics.device_type</code>.
     */
    public void setDeviceType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.click_analytics.device_type</code>.
     */
    public String getDeviceType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.click_analytics.browser</code>.
     */
    public void setBrowser(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.click_analytics.browser</code>.
     */
    public String getBrowser() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.click_analytics.operating_system</code>.
     */
    public void setOperatingSystem(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.click_analytics.operating_system</code>.
     */
    public String getOperatingSystem() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.click_analytics.geo_country</code>.
     */
    public void setGeoCountry(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.click_analytics.geo_country</code>.
     */
    public String getGeoCountry() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.click_analytics.geo_city</code>.
     */
    public void setGeoCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.click_analytics.geo_city</code>.
     */
    public String getGeoCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.click_analytics.referrer</code>.
     */
    public void setReferrer(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.click_analytics.referrer</code>.
     */
    public String getReferrer() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.click_analytics.is_bot</code>.
     */
    public void setIsBot(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.click_analytics.is_bot</code>.
     */
    public Boolean getIsBot() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.click_analytics.variant</code>.
     */
    public void setVariant(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.click_analytics.variant</code>.
     */
    public String getVariant() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.click_analytics.utm_source</code>.
     */
    public void setUtmSource(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.click_analytics.utm_source</code>.
     */
    public String getUtmSource() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.click_analytics.utm_medium</code>.
     */
    public void setUtmMedium(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.click_analytics.utm_medium</code>.
     */
    public String getUtmMedium() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.click_analytics.utm_campaign</code>.
     */
    public void setUtmCampaign(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.click_analytics.utm_campaign</code>.
     */
    public String getUtmCampaign() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.click_analytics.url_id</code>.
     */
    public void setUrlId(UUID value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.click_analytics.url_id</code>.
     */
    public UUID getUrlId() {
        return (UUID) get(15);
    }

    /**
     * Setter for <code>public.click_analytics.campaign_id</code>.
     */
    public void setCampaignId(UUID value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.click_analytics.campaign_id</code>.
     */
    public UUID getCampaignId() {
        return (UUID) get(16);
    }

    /**
     * Setter for <code>public.click_analytics.ab_test_id</code>.
     */
    public void setAbTestId(UUID value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.click_analytics.ab_test_id</code>.
     */
    public UUID getAbTestId() {
        return (UUID) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<UUID, String, OffsetDateTime, String, String, String, String, String, String, String, Boolean, String, String, String, String, UUID, UUID, UUID> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<UUID, String, OffsetDateTime, String, String, String, String, String, String, String, Boolean, String, String, String, String, UUID, UUID, UUID> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ClickAnalytics.CLICK_ANALYTICS.ID;
    }

    @Override
    public Field<String> field2() {
        return ClickAnalytics.CLICK_ANALYTICS.SHORT_CODE;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return ClickAnalytics.CLICK_ANALYTICS.TIMESTAMP;
    }

    @Override
    public Field<String> field4() {
        return ClickAnalytics.CLICK_ANALYTICS.USER_AGENT;
    }

    @Override
    public Field<String> field5() {
        return ClickAnalytics.CLICK_ANALYTICS.DEVICE_TYPE;
    }

    @Override
    public Field<String> field6() {
        return ClickAnalytics.CLICK_ANALYTICS.BROWSER;
    }

    @Override
    public Field<String> field7() {
        return ClickAnalytics.CLICK_ANALYTICS.OPERATING_SYSTEM;
    }

    @Override
    public Field<String> field8() {
        return ClickAnalytics.CLICK_ANALYTICS.GEO_COUNTRY;
    }

    @Override
    public Field<String> field9() {
        return ClickAnalytics.CLICK_ANALYTICS.GEO_CITY;
    }

    @Override
    public Field<String> field10() {
        return ClickAnalytics.CLICK_ANALYTICS.REFERRER;
    }

    @Override
    public Field<Boolean> field11() {
        return ClickAnalytics.CLICK_ANALYTICS.IS_BOT;
    }

    @Override
    public Field<String> field12() {
        return ClickAnalytics.CLICK_ANALYTICS.VARIANT;
    }

    @Override
    public Field<String> field13() {
        return ClickAnalytics.CLICK_ANALYTICS.UTM_SOURCE;
    }

    @Override
    public Field<String> field14() {
        return ClickAnalytics.CLICK_ANALYTICS.UTM_MEDIUM;
    }

    @Override
    public Field<String> field15() {
        return ClickAnalytics.CLICK_ANALYTICS.UTM_CAMPAIGN;
    }

    @Override
    public Field<UUID> field16() {
        return ClickAnalytics.CLICK_ANALYTICS.URL_ID;
    }

    @Override
    public Field<UUID> field17() {
        return ClickAnalytics.CLICK_ANALYTICS.CAMPAIGN_ID;
    }

    @Override
    public Field<UUID> field18() {
        return ClickAnalytics.CLICK_ANALYTICS.AB_TEST_ID;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getShortCode();
    }

    @Override
    public OffsetDateTime component3() {
        return getTimestamp();
    }

    @Override
    public String component4() {
        return getUserAgent();
    }

    @Override
    public String component5() {
        return getDeviceType();
    }

    @Override
    public String component6() {
        return getBrowser();
    }

    @Override
    public String component7() {
        return getOperatingSystem();
    }

    @Override
    public String component8() {
        return getGeoCountry();
    }

    @Override
    public String component9() {
        return getGeoCity();
    }

    @Override
    public String component10() {
        return getReferrer();
    }

    @Override
    public Boolean component11() {
        return getIsBot();
    }

    @Override
    public String component12() {
        return getVariant();
    }

    @Override
    public String component13() {
        return getUtmSource();
    }

    @Override
    public String component14() {
        return getUtmMedium();
    }

    @Override
    public String component15() {
        return getUtmCampaign();
    }

    @Override
    public UUID component16() {
        return getUrlId();
    }

    @Override
    public UUID component17() {
        return getCampaignId();
    }

    @Override
    public UUID component18() {
        return getAbTestId();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getShortCode();
    }

    @Override
    public OffsetDateTime value3() {
        return getTimestamp();
    }

    @Override
    public String value4() {
        return getUserAgent();
    }

    @Override
    public String value5() {
        return getDeviceType();
    }

    @Override
    public String value6() {
        return getBrowser();
    }

    @Override
    public String value7() {
        return getOperatingSystem();
    }

    @Override
    public String value8() {
        return getGeoCountry();
    }

    @Override
    public String value9() {
        return getGeoCity();
    }

    @Override
    public String value10() {
        return getReferrer();
    }

    @Override
    public Boolean value11() {
        return getIsBot();
    }

    @Override
    public String value12() {
        return getVariant();
    }

    @Override
    public String value13() {
        return getUtmSource();
    }

    @Override
    public String value14() {
        return getUtmMedium();
    }

    @Override
    public String value15() {
        return getUtmCampaign();
    }

    @Override
    public UUID value16() {
        return getUrlId();
    }

    @Override
    public UUID value17() {
        return getCampaignId();
    }

    @Override
    public UUID value18() {
        return getAbTestId();
    }

    @Override
    public ClickAnalyticsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value2(String value) {
        setShortCode(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value3(OffsetDateTime value) {
        setTimestamp(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value4(String value) {
        setUserAgent(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value5(String value) {
        setDeviceType(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value6(String value) {
        setBrowser(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value7(String value) {
        setOperatingSystem(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value8(String value) {
        setGeoCountry(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value9(String value) {
        setGeoCity(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value10(String value) {
        setReferrer(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value11(Boolean value) {
        setIsBot(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value12(String value) {
        setVariant(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value13(String value) {
        setUtmSource(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value14(String value) {
        setUtmMedium(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value15(String value) {
        setUtmCampaign(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value16(UUID value) {
        setUrlId(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value17(UUID value) {
        setCampaignId(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord value18(UUID value) {
        setAbTestId(value);
        return this;
    }

    @Override
    public ClickAnalyticsRecord values(UUID value1, String value2, OffsetDateTime value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, Boolean value11, String value12, String value13, String value14, String value15, UUID value16, UUID value17, UUID value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClickAnalyticsRecord
     */
    public ClickAnalyticsRecord() {
        super(ClickAnalytics.CLICK_ANALYTICS);
    }

    /**
     * Create a detached, initialised ClickAnalyticsRecord
     */
    public ClickAnalyticsRecord(UUID id, String shortCode, OffsetDateTime timestamp, String userAgent, String deviceType, String browser, String operatingSystem, String geoCountry, String geoCity, String referrer, Boolean isBot, String variant, String utmSource, String utmMedium, String utmCampaign, UUID urlId, UUID campaignId, UUID abTestId) {
        super(ClickAnalytics.CLICK_ANALYTICS);

        setId(id);
        setShortCode(shortCode);
        setTimestamp(timestamp);
        setUserAgent(userAgent);
        setDeviceType(deviceType);
        setBrowser(browser);
        setOperatingSystem(operatingSystem);
        setGeoCountry(geoCountry);
        setGeoCity(geoCity);
        setReferrer(referrer);
        setIsBot(isBot);
        setVariant(variant);
        setUtmSource(utmSource);
        setUtmMedium(utmMedium);
        setUtmCampaign(utmCampaign);
        setUrlId(urlId);
        setCampaignId(campaignId);
        setAbTestId(abTestId);
        resetChangedOnNotNull();
    }
}
