/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq;


import com.urlshortener.core.jooq.tables.AbTests;
import com.urlshortener.core.jooq.tables.AbVariants;
import com.urlshortener.core.jooq.tables.Campaigns;
import com.urlshortener.core.jooq.tables.UrlMappings;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_AB_TESTS_URL_MAPPING = Internal.createIndex(DSL.name("idx_ab_tests_url_mapping"), AbTests.AB_TESTS, new OrderField[] { AbTests.AB_TESTS.URL_MAPPING_ID }, false);
    public static final Index IDX_AB_VARIANTS_TEST_ID = Internal.createIndex(DSL.name("idx_ab_variants_test_id"), AbVariants.AB_VARIANTS, new OrderField[] { AbVariants.AB_VARIANTS.AB_TEST_ID }, false);
    public static final Index IDX_CAMPAIGNS_USER_NAME = Internal.createIndex(DSL.name("idx_campaigns_user_name"), Campaigns.CAMPAIGNS, new OrderField[] { Campaigns.CAMPAIGNS.USER_ID, Campaigns.CAMPAIGNS.NAME }, true);
    public static final Index IDX_CAMPAIGNS_USERS_ID = Internal.createIndex(DSL.name("idx_campaigns_users_id"), Campaigns.CAMPAIGNS, new OrderField[] { Campaigns.CAMPAIGNS.USER_ID }, false);
    public static final Index IDX_URL_MAPPINGS_CAMPAIGN_ID = Internal.createIndex(DSL.name("idx_url_mappings_campaign_id"), UrlMappings.URL_MAPPINGS, new OrderField[] { UrlMappings.URL_MAPPINGS.CAMPAIGN_ID }, false);
    public static final Index IDX_URL_MAPPINGS_SHORT_CODE = Internal.createIndex(DSL.name("idx_url_mappings_short_code"), UrlMappings.URL_MAPPINGS, new OrderField[] { UrlMappings.URL_MAPPINGS.SHORT_CODE }, false);
    public static final Index IDX_URL_MAPPINGS_USER_ID = Internal.createIndex(DSL.name("idx_url_mappings_user_id"), UrlMappings.URL_MAPPINGS, new OrderField[] { UrlMappings.URL_MAPPINGS.USER_ID }, false);
}
