/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq;


import com.urlshortener.core.jooq.tables.AbTests;
import com.urlshortener.core.jooq.tables.AbVariants;
import com.urlshortener.core.jooq.tables.Campaigns;
import com.urlshortener.core.jooq.tables.UrlMappings;
import com.urlshortener.core.jooq.tables.records.AbTestsRecord;
import com.urlshortener.core.jooq.tables.records.AbVariantsRecord;
import com.urlshortener.core.jooq.tables.records.CampaignsRecord;
import com.urlshortener.core.jooq.tables.records.UrlMappingsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AbTestsRecord> AB_TESTS_PKEY = Internal.createUniqueKey(AbTests.AB_TESTS, DSL.name("ab_tests_pkey"), new TableField[] { AbTests.AB_TESTS.ID }, true);
    public static final UniqueKey<AbTestsRecord> AB_TESTS_URL_MAPPING_ID_KEY = Internal.createUniqueKey(AbTests.AB_TESTS, DSL.name("ab_tests_url_mapping_id_key"), new TableField[] { AbTests.AB_TESTS.URL_MAPPING_ID }, true);
    public static final UniqueKey<AbVariantsRecord> AB_VARIANTS_PKEY = Internal.createUniqueKey(AbVariants.AB_VARIANTS, DSL.name("ab_variants_pkey"), new TableField[] { AbVariants.AB_VARIANTS.ID }, true);
    public static final UniqueKey<CampaignsRecord> CAMPAIGNS_PKEY = Internal.createUniqueKey(Campaigns.CAMPAIGNS, DSL.name("campaigns_pkey"), new TableField[] { Campaigns.CAMPAIGNS.ID }, true);
    public static final UniqueKey<UrlMappingsRecord> URL_MAPPINGS_PKEY = Internal.createUniqueKey(UrlMappings.URL_MAPPINGS, DSL.name("url_mappings_pkey"), new TableField[] { UrlMappings.URL_MAPPINGS.ID }, true);
    public static final UniqueKey<UrlMappingsRecord> URL_MAPPINGS_SHORT_CODE_KEY = Internal.createUniqueKey(UrlMappings.URL_MAPPINGS, DSL.name("url_mappings_short_code_key"), new TableField[] { UrlMappings.URL_MAPPINGS.SHORT_CODE }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AbTestsRecord, UrlMappingsRecord> AB_TESTS__AB_TESTS_URL_MAPPING_ID_FKEY = Internal.createForeignKey(AbTests.AB_TESTS, DSL.name("ab_tests_url_mapping_id_fkey"), new TableField[] { AbTests.AB_TESTS.URL_MAPPING_ID }, Keys.URL_MAPPINGS_PKEY, new TableField[] { UrlMappings.URL_MAPPINGS.ID }, true);
    public static final ForeignKey<AbVariantsRecord, AbTestsRecord> AB_VARIANTS__AB_VARIANTS_AB_TEST_ID_FKEY = Internal.createForeignKey(AbVariants.AB_VARIANTS, DSL.name("ab_variants_ab_test_id_fkey"), new TableField[] { AbVariants.AB_VARIANTS.AB_TEST_ID }, Keys.AB_TESTS_PKEY, new TableField[] { AbTests.AB_TESTS.ID }, true);
    public static final ForeignKey<UrlMappingsRecord, CampaignsRecord> URL_MAPPINGS__URL_MAPPINGS_CAMPAIGN_ID_FKEY = Internal.createForeignKey(UrlMappings.URL_MAPPINGS, DSL.name("url_mappings_campaign_id_fkey"), new TableField[] { UrlMappings.URL_MAPPINGS.CAMPAIGN_ID }, Keys.CAMPAIGNS_PKEY, new TableField[] { Campaigns.CAMPAIGNS.ID }, true);
}
