/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq;


import com.urlshortener.core.jooq.tables.AbTests;
import com.urlshortener.core.jooq.tables.AbVariants;
import com.urlshortener.core.jooq.tables.Campaigns;
import com.urlshortener.core.jooq.tables.UrlMappings;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.ab_tests</code>.
     */
    public final AbTests AB_TESTS = AbTests.AB_TESTS;

    /**
     * The table <code>public.ab_variants</code>.
     */
    public final AbVariants AB_VARIANTS = AbVariants.AB_VARIANTS;

    /**
     * The table <code>public.campaigns</code>.
     */
    public final Campaigns CAMPAIGNS = Campaigns.CAMPAIGNS;

    /**
     * The table <code>public.url_mappings</code>.
     */
    public final UrlMappings URL_MAPPINGS = UrlMappings.URL_MAPPINGS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AbTests.AB_TESTS,
            AbVariants.AB_VARIANTS,
            Campaigns.CAMPAIGNS,
            UrlMappings.URL_MAPPINGS
        );
    }
}
