/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.core.jooq;


import com.urlshortener.core.jooq.tables.AbTests;
import com.urlshortener.core.jooq.tables.AbVariants;
import com.urlshortener.core.jooq.tables.Campaigns;
import com.urlshortener.core.jooq.tables.UrlMappings;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.ab_tests</code>.
     */
    public static final AbTests AB_TESTS = AbTests.AB_TESTS;

    /**
     * The table <code>public.ab_variants</code>.
     */
    public static final AbVariants AB_VARIANTS = AbVariants.AB_VARIANTS;

    /**
     * The table <code>public.campaigns</code>.
     */
    public static final Campaigns CAMPAIGNS = Campaigns.CAMPAIGNS;

    /**
     * The table <code>public.url_mappings</code>.
     */
    public static final UrlMappings URL_MAPPINGS = UrlMappings.URL_MAPPINGS;
}
