/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.analytics.jooq;


import com.urlshortener.analytics.jooq.tables.ClickAnalytics;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_CLICK_ANALYTICS_AB_TEST_ID = Internal.createIndex(DSL.name("idx_click_analytics_ab_test_id"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.AB_TEST_ID }, false);
    public static final Index IDX_CLICK_ANALYTICS_CAMPAIGN_ID = Internal.createIndex(DSL.name("idx_click_analytics_campaign_id"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.CAMPAIGN_ID }, false);
    public static final Index IDX_CLICK_ANALYTICS_SHORT_CODE = Internal.createIndex(DSL.name("idx_click_analytics_short_code"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.SHORT_CODE }, false);
    public static final Index IDX_CLICK_ANALYTICS_SHORT_CODE_VARIANT = Internal.createIndex(DSL.name("idx_click_analytics_short_code_variant"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.SHORT_CODE, ClickAnalytics.CLICK_ANALYTICS.VARIANT }, false);
    public static final Index IDX_CLICK_ANALYTICS_TIMESTAMP = Internal.createIndex(DSL.name("idx_click_analytics_timestamp"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.TIMESTAMP }, false);
    public static final Index IDX_CLICK_ANALYTICS_URL_ID = Internal.createIndex(DSL.name("idx_click_analytics_url_id"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.URL_ID }, false);
    public static final Index IDX_CLICK_ANALYTICS_UTM_CAMPAIGN = Internal.createIndex(DSL.name("idx_click_analytics_utm_campaign"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.SHORT_CODE, ClickAnalytics.CLICK_ANALYTICS.UTM_CAMPAIGN }, false);
    public static final Index IDX_CLICK_ANALYTICS_UTM_SOURCE = Internal.createIndex(DSL.name("idx_click_analytics_utm_source"), ClickAnalytics.CLICK_ANALYTICS, new OrderField[] { ClickAnalytics.CLICK_ANALYTICS.SHORT_CODE, ClickAnalytics.CLICK_ANALYTICS.UTM_SOURCE }, false);
}
