/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.analytics.jooq;


import com.urlshortener.analytics.jooq.tables.ClickAnalytics;
import com.urlshortener.analytics.jooq.tables.records.ClickAnalyticsRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClickAnalyticsRecord> CLICK_ANALYTICS_PKEY = Internal.createUniqueKey(ClickAnalytics.CLICK_ANALYTICS, DSL.name("click_analytics_pkey"), new TableField[] { ClickAnalytics.CLICK_ANALYTICS.ID }, true);
}
