/*
 * This file is generated by jOOQ.
 */
package com.urlshortener.analytics.jooq;


import com.urlshortener.analytics.jooq.tables.ClickAnalytics;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.click_analytics</code>.
     */
    public static final ClickAnalytics CLICK_ANALYTICS = ClickAnalytics.CLICK_ANALYTICS;
}
